import type { Template } from "./types"

export const templates: Template[] = [
  {
    id: "1",
    name: "Minimalist Portfolio",
    description: "A clean, minimal portfolio template for developers and designers.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["react", "tailwind", "responsive"],
    downloadUrl: "#download-link-1",
    githubUrl: "https://github.com/",
  },
  {
    id: "2",
    name: "Creative Showcase",
    description: "Showcase your creative work with this visually appealing template.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["nextjs", "framer-motion", "responsive"],
    downloadUrl: "#download-link-2",
    githubUrl: "https://github.com/",
  },
  {
    id: "3",
    name: "Developer CV",
    description: "A professional CV template for software developers with project showcases.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["html", "css", "bootstrap"],
    downloadUrl: "#download-link-3",
    githubUrl: "https://github.com/",
  },
  {
    id: "4",
    name: "Photography Portfolio",
    description: "Perfect for photographers to showcase their work with large image displays.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["react", "grid-layout", "gallery"],
    downloadUrl: "#download-link-4",
    githubUrl: "https://github.com/",
  },
  {
    id: "5",
    name: "Freelancer Landing",
    description: "A landing page template for freelancers to attract potential clients.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["nextjs", "tailwind", "animation"],
    downloadUrl: "#download-link-5",
    githubUrl: "https://github.com/",
  },
  {
    id: "6",
    name: "Simple Blog",
    description: "A clean blog template for developers who want to share their knowledge.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["html", "css", "responsive"],
    downloadUrl: "#download-link-6",
    githubUrl: "https://github.com/",
  },
  {
    id: "7",
    name: "Interactive Resume",
    description: "An interactive resume template with animations and visual elements.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["react", "gsap", "interactive"],
    downloadUrl: "#download-link-7",
    githubUrl: "https://github.com/",
  },
  {
    id: "8",
    name: "Agency Portfolio",
    description: "A professional template for agencies to showcase their services and work.",
    thumbnail: "/placeholder.svg?height=300&width=500",
    tags: ["nextjs", "tailwind", "responsive"],
    downloadUrl: "#download-link-8",
    githubUrl: "https://github.com/",
  },
]

